@baseUrl = http://192.168.5.173:8100/mysite

###

POST {{baseUrl}}/api/admin/product-seed
Content-Type: application/json

{
}

###

GET {{baseUrl}}/api/admin/products

###

GET {{baseUrl}}/api/admin/product/2

###

GET {{baseUrl}}/api/product/1

###

GET {{baseUrl}}/api/product/soccer/1

###

GET {{baseUrl}}/api/product/categories
