# Generated by Django 3.1.6 on 2021-02-04 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('line1', models.CharField(max_length=300)),
                ('line2', models.CharField(blank=True, max_length=300, null=True)),
                ('line3', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=300)),
                ('postcode', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(max_length=200)),
                ('giftwrap', models.BooleanField()),
                ('shipped', models.BooleanField()),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='CartLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='cartline_order', to='app.order')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='cartline_product', to='app.product')),
            ],
            options={
                'db_table': 'cartline',
            },
        ),
    ]
